package container

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// MinimalDockerfile renders a strike-oriented Dockerfile from Config.
// Full template eject + project dep detection is E12.3 (#585); this is enough
// for build/launch lifecycle tests and a usable default image.
func MinimalDockerfile(cfg Config, hostUID int) string {
	base := cfg.baseImage()
	shell := cfg.shell()
	mount := cfg.mountPath()
	var b strings.Builder
	b.WriteString("# syntax=docker/dockerfile:1\n")
	b.WriteString("# Generated by strike — container foundation (E12.1); prefer `strike container eject` (E12.3)\n")
	fmt.Fprintf(&b, "FROM %s\n\n", base)
	b.WriteString("ARG DEBIAN_FRONTEND=noninteractive\n")
	fmt.Fprintf(&b, "ARG HOST_UID=%d\n\n", hostUID)
	b.WriteString("RUN apt-get update && apt-get install -y --no-install-recommends \\\n")
	b.WriteString("    ca-certificates curl git sudo \\\n")
	if len(cfg.AptPackages) > 0 {
		for _, p := range cfg.AptPackages {
			fmt.Fprintf(&b, "    %s \\\n", p)
		}
	}
	b.WriteString("    && rm -rf /var/lib/apt/lists/*\n\n")
	if hostUID > 0 {
		b.WriteString("RUN set -eux; \\\n")
		b.WriteString("    if ! getent passwd strike >/dev/null; then \\\n")
		b.WriteString("      useradd --create-home --shell /bin/bash --uid \"${HOST_UID}\" strike; \\\n")
		b.WriteString("    fi; \\\n")
		b.WriteString("    echo 'strike ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/strike; \\\n")
		b.WriteString("    chmod 0440 /etc/sudoers.d/strike\n\n")
		fmt.Fprintf(&b, "USER strike\n")
		b.WriteString("WORKDIR /home/strike\n\n")
	}
	fmt.Fprintf(&b, "ENV STRIKE_WORKSPACE=%s\n", mount)
	fmt.Fprintf(&b, "WORKDIR %s\n", mount)
	// Keep container alive for exec/attach; launch overrides with strike binary later.
	fmt.Fprintf(&b, "SHELL [%q, \"-c\"]\n", shell)
	b.WriteString("CMD [\"sleep\", \"infinity\"]\n")
	return b.String()
}

// ResolveDockerfileBody returns Dockerfile text from path override or template.
func ResolveDockerfileBody(cfg Config, repoDir string, hostUID int) (string, error) {
	if cfg.Dockerfile != "" {
		path := cfg.Dockerfile
		if !filepath.IsAbs(path) {
			path = filepath.Join(repoDir, path)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return "", fmt.Errorf("read Dockerfile %s: %w", path, err)
		}
		return string(data), nil
	}
	return MinimalDockerfile(cfg, hostUID), nil
}

// HostUID returns the current user id for non-root container mapping (0 on failure).
func HostUID() int {
	// os/user would work; keep dependency-free via env common in CI.
	if s := os.Getenv("SUDO_UID"); s != "" {
		if n, err := strconv.Atoi(s); err == nil {
			return n
		}
	}
	return osGetuid()
}
