package container

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderDockerfileHeaderAndHash(t *testing.T) {
	cfg := DefaultConfig()
	cfg.TemplateVersion = "vtest"
	body, hash, err := RenderDockerfile(cfg, t.TempDir(), "vtest")
	if err != nil {
		t.Fatal(err)
	}
	if len(hash) != 64 {
		t.Fatalf("hash len %d", len(hash))
	}
	if !strings.Contains(body, "# strike-config-hash: "+hash) {
		t.Fatalf("missing hash header:\n%s", body)
	}
	if !strings.HasPrefix(body, "# syntax=") {
		t.Fatalf("syntax line: %q", body[:40])
	}
	got, ok := ParseConfigHash(body)
	if !ok || got != hash {
		t.Fatalf("parse %q %v", got, ok)
	}
}

func TestEjectWriteAndUnchangedAndDrift(t *testing.T) {
	repo := t.TempDir()
	cfg := DefaultConfig()
	cfg.AptPackages = []string{"make"}

	res, err := Eject(cfg, repo, EjectOpts{Version: "v1"})
	if err != nil || !res.Wrote {
		t.Fatalf("%+v %v", res, err)
	}
	path := filepath.Join(repo, DefaultEjectName)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "make") {
		t.Fatalf("body: %s", data)
	}

	res2, err := Eject(cfg, repo, EjectOpts{Version: "v1"})
	if err != nil || !res2.Unchanged || res2.Wrote {
		t.Fatalf("unchanged: %+v %v", res2, err)
	}

	cfg.AptPackages = []string{"curl"}
	_, err = Eject(cfg, repo, EjectOpts{Version: "v1"})
	if !errors.Is(err, ErrDockerfileDrift) {
		t.Fatalf("want drift, got %v", err)
	}
	res3, err := Eject(cfg, repo, EjectOpts{Version: "v1", Force: true})
	if err != nil || !res3.Wrote || !res3.Drifted {
		t.Fatalf("force: %+v %v", res3, err)
	}

	drifted, _, _, err := CheckDrift(cfg, repo, "", "v1")
	if err != nil || drifted {
		t.Fatalf("check after force: drifted=%v err=%v", drifted, err)
	}
}

func TestEjectCustomOutAndDockerfilePath(t *testing.T) {
	repo := t.TempDir()
	hand := filepath.Join(repo, "Dockerfile.custom")
	if err := os.WriteFile(hand, []byte("# syntax=docker/dockerfile:1\nFROM alpine:3\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg := DefaultConfig()
	cfg.Dockerfile = "Dockerfile.custom"
	out := "out/Docker.dev"
	res, err := Eject(cfg, repo, EjectOpts{Out: out, Version: "v1"})
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(repo, out))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "FROM alpine:3") {
		t.Fatalf("%s", data)
	}
	if res.Hash == "" {
		t.Fatal("empty hash")
	}
}

func TestInjectHeaderIdempotent(t *testing.T) {
	raw := "# syntax=docker/dockerfile:1\nFROM x\n"
	h1 := EjectHeader("v1", "abc")
	once := InjectHeader(raw, h1)
	twice := InjectHeader(once, h1)
	// should not stack infinite headers
	if strings.Count(twice, "# Generated by strike") != 1 {
		t.Fatalf("stacked:\n%s", twice)
	}
}
