//go:build darwin

package sandbox

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
)

const (
	backendSeatbelt = "sandbox-exec"
	seatbeltPath    = "/usr/bin/sandbox-exec"
)

var (
	profileMu        sync.Mutex
	profileCache     = map[string]string{} // key -> profile file path
	seatbeltResolved string                // absolute launcher from successful probe
)

func probePlatform() availInfo {
	// Prefer the system binary; a PATH hijack of sandbox-exec would be root-equivalent.
	path := seatbeltPath
	if st, err := os.Stat(path); err != nil || st.IsDir() {
		if p, err := exec.LookPath(backendSeatbelt); err == nil {
			path = p
		} else {
			return availInfo{
				warn: "sandbox-exec not found; bash runs unsandboxed",
			}
		}
	}
	// Minimal apply probe: deny-default profile that still allows true(1).
	probeProfile := `(version 1)
(deny default)
(allow process-exec)
(allow process-fork)
(allow sysctl-read)
(allow file-read*)
(allow file-write* (literal "/dev/null"))
`
	f, err := os.CreateTemp("", "strike-sandbox-probe-*.sb")
	if err != nil {
		return availInfo{
			warn: "sandbox-exec probe failed (temp profile); bash runs unsandboxed",
		}
	}
	probePath := f.Name()
	_, werr := f.WriteString(probeProfile)
	cerr := f.Close()
	defer os.Remove(probePath)
	if werr != nil || cerr != nil {
		return availInfo{
			warn: "sandbox-exec probe failed (temp profile); bash runs unsandboxed",
		}
	}
	cmd := exec.Command(path, "-f", probePath, "true")
	if err := cmd.Run(); err != nil {
		return availInfo{
			warn: "sandbox-exec is present but cannot apply a seatbelt profile; bash runs unsandboxed",
		}
	}
	seatbeltResolved = path
	return availInfo{ok: true, name: backendSeatbelt}
}

// wrapPlatform builds: sandbox-exec -f <profile> <argv...>
// Profile is parameterized on the session worktree root for workspace-write.
func wrapPlatform(argv []string, policy Policy) []string {
	if len(argv) == 0 {
		return nil
	}
	profilePath, err := profileFile(policy)
	if err != nil || profilePath == "" {
		return nil
	}
	path := seatbeltResolved
	if path == "" {
		path = seatbeltPath
		if st, err := os.Stat(path); err != nil || st.IsDir() {
			if p, err := exec.LookPath(backendSeatbelt); err == nil {
				path = p
			} else {
				return nil
			}
		}
	}
	out := make([]string, 0, 3+len(argv))
	out = append(out, path, "-f", profilePath)
	out = append(out, argv...)
	return out
}

func profileFile(policy Policy) (string, error) {
	wd := absWorkDir(policy.WorkDir)
	key := fmt.Sprintf("%d|%s", policy.Mode, wd)
	profileMu.Lock()
	defer profileMu.Unlock()
	if p, ok := profileCache[key]; ok {
		if _, err := os.Stat(p); err == nil {
			return p, nil
		}
		delete(profileCache, key)
	}
	body := buildSeatbeltProfile(policy.Mode, wd)
	f, err := os.CreateTemp("", "strike-sandbox-*.sb")
	if err != nil {
		return "", err
	}
	path := f.Name()
	if _, err := f.WriteString(body); err != nil {
		f.Close()
		os.Remove(path)
		return "", err
	}
	if err := f.Close(); err != nil {
		os.Remove(path)
		return "", err
	}
	// 0600 already from CreateTemp; keep profile private.
	profileCache[key] = path
	return path, nil
}

func buildSeatbeltProfile(mode Mode, workDir string) string {
	var b strings.Builder
	b.WriteString(`(version 1)
; Generated by strike internal/sandbox — do not edit.
(deny default)

; Process lifecycle
(allow process-exec)
(allow process-fork)
(allow signal (target self))
(allow signal (target same-sandbox))

; Basic sysctl / mach needed by dynamic linkers and shells
(allow sysctl-read)
(allow mach-lookup
  (global-name "com.apple.system.opendirectoryd.libinfo")
  (global-name "com.apple.corefoundation.cfprefsd.server")
  (global-name "com.apple.cfprefsd.daemon")
  (global-name "com.apple.cfprefsd.agent")
)

; Read the filesystem; writes are scoped below.
(allow file-read*)
(allow file-write-data
  (require-all
    (path "/dev/null")
    (vnode-type CHARACTER-DEVICE)))
(allow file-ioctl
  (literal "/dev/null")
  (literal "/dev/zero")
  (literal "/dev/tty")
  (literal "/dev/ptmx"))
(allow pseudo-tty)

; Temp dirs — compilers and shells need scratch space.
(allow file-write* (subpath "/tmp"))
(allow file-write* (subpath "/private/tmp"))
(allow file-write* (subpath "/var/tmp"))
(allow file-write* (subpath "/private/var/tmp"))
`)
	// Network is denied by default (no allow network-*).
	if mode == ModeWorkspaceWrite && workDir != "" {
		// Seatbelt subpath match; escape " and \ in the path literal.
		escaped := seatbeltEscape(workDir)
		fmt.Fprintf(&b, "\n; Session workspace (writable)\n(allow file-write* (subpath \"%s\"))\n", escaped)
		// macOS often surfaces /var as /private/var — allow both when applicable.
		if strings.HasPrefix(workDir, "/var/") {
			alt := "/private" + workDir
			fmt.Fprintf(&b, "(allow file-write* (subpath \"%s\"))\n", seatbeltEscape(alt))
		}
		if strings.HasPrefix(workDir, "/tmp/") {
			alt := "/private" + workDir
			fmt.Fprintf(&b, "(allow file-write* (subpath \"%s\"))\n", seatbeltEscape(alt))
		}
	}
	return b.String()
}

func seatbeltEscape(p string) string {
	p = strings.ReplaceAll(p, `\`, `\\`)
	p = strings.ReplaceAll(p, `"`, `\"`)
	return p
}

func absWorkDir(workDir string) string {
	workDir = strings.TrimSpace(workDir)
	if workDir == "" {
		return ""
	}
	clean := filepath.Clean(workDir)
	abs, err := filepath.Abs(clean)
	if err != nil {
		return clean
	}
	if real, err := filepath.EvalSymlinks(abs); err == nil && real != "" {
		return real
	}
	return abs
}
