//go:build darwin

package sandbox

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
)

const (
	backendSeatbelt = "sandbox-exec"
	seatbeltPath    = "/usr/bin/sandbox-exec"
)

var (
	profileMu        sync.Mutex
	profileCache     = map[string]string{} // key -> profile file path
	seatbeltResolved string                // absolute launcher from successful probe
)

func clearLauncherForTest() { seatbeltResolved = "" }

func probePlatform() availInfo {
	// Prefer the system binary; a PATH hijack of sandbox-exec would be root-equivalent.
	path := seatbeltPath
	if st, err := os.Stat(path); err != nil || st.IsDir() {
		if p, err := exec.LookPath(backendSeatbelt); err == nil {
			path = p
		} else {
			return availInfo{
				warn: "sandbox-exec not found; bash runs unsandboxed",
			}
		}
	}
	// Minimal apply probe: deny-default profile that still allows true(1).
	probeProfile := `(version 1)
(deny default)
(allow process-exec)
(allow process-fork)
(allow sysctl-read)
(allow file-read*)
(allow file-write* (literal "/dev/null"))
`
	f, err := os.CreateTemp("", "strike-sandbox-probe-*.sb")
	if err != nil {
		return availInfo{
			warn: "sandbox-exec probe failed (temp profile); bash runs unsandboxed",
		}
	}
	probePath := f.Name()
	_, werr := f.WriteString(probeProfile)
	cerr := f.Close()
	defer os.Remove(probePath)
	if werr != nil || cerr != nil {
		return availInfo{
			warn: "sandbox-exec probe failed (temp profile); bash runs unsandboxed",
		}
	}
	cmd := exec.Command(path, "-f", probePath, "true")
	if err := cmd.Run(); err != nil {
		return availInfo{
			warn: "sandbox-exec is present but cannot apply a seatbelt profile; bash runs unsandboxed",
		}
	}
	seatbeltResolved = path
	return availInfo{ok: true, name: backendSeatbelt}
}

// wrapPlatform builds: sandbox-exec -f <profile> <argv...>
// Profile is parameterized on the session worktree root for workspace-write.
func wrapPlatform(argv []string, policy Policy) []string {
	if len(argv) == 0 {
		return nil
	}
	profilePath, err := profileFile(policy)
	if err != nil || profilePath == "" {
		return nil
	}
	path := seatbeltResolved
	if path == "" {
		path = seatbeltPath
		if st, err := os.Stat(path); err != nil || st.IsDir() {
			if p, err := exec.LookPath(backendSeatbelt); err == nil {
				path = p
			} else {
				return nil
			}
		}
	}
	out := make([]string, 0, 3+len(argv))
	out = append(out, path, "-f", profilePath)
	out = append(out, argv...)
	return out
}

func profileFile(policy Policy) (string, error) {
	wd := absWorkDir(policy.WorkDir)
	key := policyCacheKey(policy, wd)
	profileMu.Lock()
	defer profileMu.Unlock()
	if p, ok := profileCache[key]; ok {
		if _, err := os.Stat(p); err == nil {
			return p, nil
		}
		delete(profileCache, key)
	}
	body := buildSeatbeltProfile(policy, wd)
	f, err := os.CreateTemp("", "strike-sandbox-*.sb")
	if err != nil {
		return "", err
	}
	path := f.Name()
	if _, err := f.WriteString(body); err != nil {
		f.Close()
		os.Remove(path)
		return "", err
	}
	if err := f.Close(); err != nil {
		os.Remove(path)
		return "", err
	}
	// 0600 already from CreateTemp; keep profile private.
	profileCache[key] = path
	return path, nil
}

func policyCacheKey(policy Policy, wd string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%d|%s|%t|%t", policy.Mode, wd, policy.NoWorkspaceWrite, policy.Network)
	for _, g := range policy.DenyWriteGlobs {
		b.WriteByte('|')
		b.WriteString(g)
	}
	for _, p := range policy.DenyWritePaths {
		b.WriteByte('|')
		b.WriteString(p)
	}
	return b.String()
}

func profileText(policy Policy) string {
	if policy.Mode == ModeOff {
		return "(none — sandbox off)\n"
	}
	return buildSeatbeltProfile(policy, absWorkDir(policy.WorkDir))
}

func buildSeatbeltProfile(policy Policy, workDir string) string {
	mode := policy.Mode
	var b strings.Builder
	b.WriteString(`(version 1)
; Generated by strike internal/sandbox — do not edit.
(deny default)

; Process lifecycle
(allow process-exec)
(allow process-fork)
(allow signal (target self))
(allow signal (target same-sandbox))

; Basic sysctl / mach needed by dynamic linkers and shells
(allow sysctl-read)
(allow mach-lookup
  (global-name "com.apple.system.opendirectoryd.libinfo")
  (global-name "com.apple.corefoundation.cfprefsd.server")
  (global-name "com.apple.cfprefsd.daemon")
  (global-name "com.apple.cfprefsd.agent")
)

; Read the filesystem; writes are scoped below.
(allow file-read*)
(allow file-write-data
  (require-all
    (path "/dev/null")
    (vnode-type CHARACTER-DEVICE)))
(allow file-ioctl
  (literal "/dev/null")
  (literal "/dev/zero")
  (literal "/dev/tty")
  (literal "/dev/ptmx"))
(allow pseudo-tty)

; Temp dirs — compilers and shells need scratch space.
(allow file-write* (subpath "/tmp"))
(allow file-write* (subpath "/private/tmp"))
(allow file-write* (subpath "/var/tmp"))
(allow file-write* (subpath "/private/var/tmp"))
`)
	// Additional shared writable roots (TMPDIR, caches, …) — skip paths already
	// covered by the hard-coded temp rules above.
	for _, p := range SharedWritablePaths(workDir, mode == ModeWorkspaceWrite && !policy.NoWorkspaceWrite) {
		switch p {
		case "/tmp", "/private/tmp", "/var/tmp", "/private/var/tmp":
			continue
		}
		fmt.Fprintf(&b, "(allow file-write* (subpath \"%s\"))\n", seatbeltEscape(p))
	}
	if policy.Network {
		b.WriteString(`
; Network (host networking; off only when webfetch+mcp deny *)
(allow network-outbound)
(allow network-inbound)
(allow system-socket)
`)
	}
	// When Network is false, deny-default omits network-* (no outbound/inbound).
	if mode == ModeWorkspaceWrite && !policy.NoWorkspaceWrite && workDir != "" {
		// Seatbelt subpath match; escape " and \ in the path literal.
		escaped := seatbeltEscape(workDir)
		fmt.Fprintf(&b, "\n; Session workspace (writable)\n(allow file-write* (subpath \"%s\"))\n", escaped)
		// macOS often surfaces /var as /private/var — allow both when applicable.
		if strings.HasPrefix(workDir, "/var/") {
			alt := "/private" + workDir
			fmt.Fprintf(&b, "(allow file-write* (subpath \"%s\"))\n", seatbeltEscape(alt))
		}
		if strings.HasPrefix(workDir, "/tmp/") {
			alt := "/private" + workDir
			fmt.Fprintf(&b, "(allow file-write* (subpath \"%s\"))\n", seatbeltEscape(alt))
		}
	}

	// Permission-compiled write denials (after allows so they win).
	if len(policy.DenyWriteGlobs) > 0 || len(policy.DenyWritePaths) > 0 {
		b.WriteString("\n; Write denials compiled from permission rules\n")
	}
	for _, g := range policy.DenyWriteGlobs {
		g = strings.TrimSpace(g)
		if g == "" || g == "*" {
			continue
		}
		re := globToSeatbeltRegex(g, workDir)
		if re == "" {
			continue
		}
		fmt.Fprintf(&b, "(deny file-write* (regex \"%s\"))\n", seatbeltEscape(re))
	}
	for _, p := range existingDenyPaths(policy.DenyWritePaths) {
		fmt.Fprintf(&b, "(deny file-write* (subpath \"%s\"))\n", seatbeltEscape(p))
		fmt.Fprintf(&b, "(deny file-write* (literal \"%s\"))\n", seatbeltEscape(p))
	}
	return b.String()
}

// globToSeatbeltRegex converts a doublestar-style permission pattern into a
// seatbelt regex anchored to workDir when the pattern is relative.
func globToSeatbeltRegex(pattern, workDir string) string {
	pattern = strings.TrimSpace(pattern)
	pattern = strings.TrimPrefix(pattern, "./")
	if pattern == "" || pattern == "*" {
		return ""
	}
	var b strings.Builder
	b.WriteByte('^')
	if workDir != "" && !filepath.IsAbs(pattern) {
		b.WriteString(regexp.QuoteMeta(workDir))
		if !strings.HasSuffix(workDir, "/") {
			b.WriteByte('/')
		}
	}
	b.WriteString(doublestarToRegex(pattern))
	b.WriteByte('$')
	return b.String()
}

// doublestarToRegex translates a limited doublestar glob to a path regex.
// Supports **, *, ?, and literal characters; other metacharacters are quoted.
func doublestarToRegex(pat string) string {
	var b strings.Builder
	for i := 0; i < len(pat); i++ {
		c := pat[i]
		switch c {
		case '*':
			if i+1 < len(pat) && pat[i+1] == '*' {
				// ** — match across path segments
				i++
				// consume trailing / so **/foo and **foo both work
				if i+1 < len(pat) && pat[i+1] == '/' {
					i++
					b.WriteString("(.*/)?")
				} else {
					b.WriteString(".*")
				}
			} else {
				b.WriteString("[^/]*")
			}
		case '?':
			b.WriteString("[^/]")
		case '[', ']', '{', '}', '\\':
			// Keep character classes roughly usable; escape regex specials that
			// are not intended as glob syntax beyond the basics above.
			b.WriteString(regexp.QuoteMeta(string(c)))
		default:
			if strings.ContainsRune(`.+^$|()`, rune(c)) {
				b.WriteString(regexp.QuoteMeta(string(c)))
			} else {
				b.WriteByte(c)
			}
		}
	}
	return b.String()
}

func seatbeltEscape(p string) string {
	p = strings.ReplaceAll(p, `\`, `\\`)
	p = strings.ReplaceAll(p, `"`, `\"`)
	return p
}
