package container

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// DefaultEjectName is the default on-disk Dockerfile name for eject.
const DefaultEjectName = "Dockerfile.devcontainer"

// headerHashRe matches the config-hash line in a generated header.
var headerHashRe = regexp.MustCompile(`(?m)^# strike-config-hash: ([0-9a-f]{64})\s*$`)

// EjectHeader builds the generated-file header (after optional # syntax= line).
func EjectHeader(version, configHash string) string {
	if version == "" {
		version = "dev"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by strike %s — do not edit by hand unless you own drift.\n", version)
	fmt.Fprintf(&b, "# Re-run: strike container eject\n")
	fmt.Fprintf(&b, "# strike-config-hash: %s\n", configHash)
	return b.String()
}

// InjectHeader inserts header after # syntax= / shebang, or at the top.
func InjectHeader(body, header string) string {
	header = strings.TrimRight(header, "\n") + "\n"
	lines := strings.SplitN(body, "\n", 2)
	if len(lines) >= 1 && (strings.HasPrefix(lines[0], "# syntax=") || strings.HasPrefix(lines[0], "#!")) {
		rest := ""
		if len(lines) == 2 {
			rest = lines[1]
		}
		// drop any previous generated header block at start of rest
		rest = stripLeadingGeneratedHeader(rest)
		return lines[0] + "\n" + header + rest
	}
	body = stripLeadingGeneratedHeader(body)
	return header + body
}

func stripLeadingGeneratedHeader(s string) string {
	for {
		s = strings.TrimPrefix(s, "\n")
		if strings.HasPrefix(s, "# Generated by strike") ||
			strings.HasPrefix(s, "# Re-run:") ||
			strings.HasPrefix(s, "# strike-config-hash:") ||
			strings.HasPrefix(s, "# Generated by strike —") {
			if i := strings.Index(s, "\n"); i >= 0 {
				s = s[i+1:]
				continue
			}
			return ""
		}
		return s
	}
}

// ParseConfigHash reads strike-config-hash from a Dockerfile body.
func ParseConfigHash(body string) (string, bool) {
	m := headerHashRe.FindStringSubmatch(body)
	if len(m) < 2 {
		return "", false
	}
	return m[1], true
}

// RenderDockerfile produces the full Dockerfile text for cfg (template or path).
// When cfg.Dockerfile is set, that file is the body (hand-edited path).
// version is embedded in the header and hash.
func RenderDockerfile(cfg Config, repoDir, version string) (body string, hash string, err error) {
	uid := HostUID()
	raw, err := ResolveDockerfileBody(cfg, repoDir, uid)
	if err != nil {
		return "", "", err
	}
	// Hash is over config + raw template body (without eject header) + version.
	hash, err = ComputeConfigHash(cfg, stripAllGeneratedHeaders(raw), version)
	if err != nil {
		return "", "", err
	}
	header := EjectHeader(version, hash)
	return InjectHeader(raw, header), hash, nil
}

func stripAllGeneratedHeaders(s string) string {
	// remove any generated header lines anywhere at the top block
	return stripLeadingGeneratedHeader(strings.TrimPrefix(s, "\n"))
}

// EjectOpts configures writing a Dockerfile to disk.
type EjectOpts struct {
	// Out is the output path (default Dockerfile.devcontainer under repoDir).
	Out string
	// Force overwrites a drifted or hand-edited file without error.
	Force bool
	// Version is the strike version string for the header.
	Version string
}

// EjectResult is the outcome of Eject.
type EjectResult struct {
	Path       string
	Hash       string
	Wrote      bool
	Unchanged  bool
	Drifted    bool // existing file hash != current
	MissingHdr bool // existing file had no hash header
}

// Eject writes the rendered Dockerfile to disk (default commit-friendly path).
func Eject(cfg Config, repoDir string, opts EjectOpts) (EjectResult, error) {
	out := opts.Out
	if out == "" {
		out = filepath.Join(repoDir, DefaultEjectName)
	} else if !filepath.IsAbs(out) {
		out = filepath.Join(repoDir, out)
	}
	body, hash, err := RenderDockerfile(cfg, repoDir, opts.Version)
	if err != nil {
		return EjectResult{}, err
	}
	res := EjectResult{Path: out, Hash: hash}

	existing, err := os.ReadFile(out)
	if err == nil {
		exHash, ok := ParseConfigHash(string(existing))
		if !ok {
			res.MissingHdr = true
			res.Drifted = true
		} else if exHash != hash {
			res.Drifted = true
		} else if string(existing) == body {
			res.Unchanged = true
			return res, nil
		}
		if res.Drifted && !opts.Force {
			return res, fmt.Errorf("%w: %s (have %s, want %s); re-run with --force to overwrite",
				ErrDockerfileDrift, out, shortHash(exHash), shortHash(hash))
		}
	} else if !os.IsNotExist(err) {
		return res, err
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return res, err
	}
	tmp := out + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		return res, err
	}
	if err := os.Rename(tmp, out); err != nil {
		_ = os.Remove(tmp)
		return res, err
	}
	res.Wrote = true
	return res, nil
}

// CheckDrift reports whether path's embedded hash matches current config.
func CheckDrift(cfg Config, repoDir, path, version string) (drifted bool, have, want string, err error) {
	if path == "" {
		path = filepath.Join(repoDir, DefaultEjectName)
	} else if !filepath.IsAbs(path) {
		path = filepath.Join(repoDir, path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return false, "", "", err
	}
	have, ok := ParseConfigHash(string(data))
	_, want, err = RenderDockerfile(cfg, repoDir, version)
	if err != nil {
		return false, have, "", err
	}
	if !ok || have != want {
		return true, have, want, nil
	}
	return false, have, want, nil
}

// ContentHash is a stable sha256 of body bytes (for tests).
func ContentHash(body string) string {
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:])
}

func shortHash(h string) string {
	if h == "" {
		return "(none)"
	}
	if len(h) > 12 {
		return h[:12]
	}
	return h
}

// ErrDockerfileDrift is returned when eject would overwrite a drifted file without --force.
var ErrDockerfileDrift = fmt.Errorf("dockerfile config hash drift")
