//go:build ignore

// Flatten internal/tui/app/_src/<group>/*.go into internal/tui/app/ for the Go toolchain.
// Source of truth is _src/; run: go generate ./internal/tui/app
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	srcRoot := filepath.Join(root, "_src")
	ents, err := os.ReadDir(srcRoot)
	if err != nil {
		fail(err)
	}
	// Remove previously generated flatten files (keep doc.go, gen_src.go).
	keep := map[string]bool{"doc.go": true, "gen_src.go": true, "gen_sync_test.go": true}
	rootEnts, _ := os.ReadDir(root)
	for _, e := range rootEnts {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || keep[e.Name()] {
			continue
		}
		_ = os.Remove(filepath.Join(root, e.Name()))
	}
	// Pre-#1209 flatten landed in parent internal/tui/*.go. Leftover copies
	// still compile as package tui and break go test ./... after upgrade.
	removeLegacyParentFlatten(root)
	n := 0
	for _, ent := range ents {
		if !ent.IsDir() {
			continue
		}
		dir := filepath.Join(srcRoot, ent.Name())
		files, err := os.ReadDir(dir)
		if err != nil {
			fail(err)
		}
		for _, f := range files {
			if f.IsDir() || !strings.HasSuffix(f.Name(), ".go") {
				continue
			}
			in := filepath.Join(dir, f.Name())
			out := filepath.Join(root, f.Name())
			data, err := os.ReadFile(in)
			if err != nil {
				fail(err)
			}
			// Drop stale markers, then stamp DO NOT EDIT so flattened copies
			// are obviously generated (they are also gitignored).
			data = stripGeneratedMarkers(data)
			data = withDoNotEdit(data)
			if err := os.WriteFile(out, data, 0o644); err != nil {
				fail(err)
			}
			n++
		}
	}
	fmt.Printf("gen_src: flattened %d files from _src/\n", n)
}

const doNotEditLine = "// Code generated by go generate ./internal/tui/app from _src/; DO NOT EDIT."

func stripGeneratedMarkers(b []byte) []byte {
	lines := bytes.Split(b, []byte("\n"))
	out := lines[:0]
	skipNextBlank := false
	for _, ln := range lines {
		if bytes.HasPrefix(ln, []byte("// Code origin: _src/")) {
			skipNextBlank = true
			continue
		}
		if bytes.Equal(ln, []byte(doNotEditLine)) || bytes.HasPrefix(ln, []byte("// Code generated by go generate")) {
			skipNextBlank = true
			continue
		}
		if skipNextBlank && len(ln) == 0 {
			skipNextBlank = false
			continue
		}
		skipNextBlank = false
		out = append(out, ln)
	}
	return bytes.Join(out, []byte("\n"))
}

func withDoNotEdit(b []byte) []byte {
	// Blank line after the marker so it is not part of a package doc group.
	var buf bytes.Buffer
	buf.WriteString(doNotEditLine)
	buf.WriteString("\n\n")
	buf.Write(b)
	if len(b) == 0 || b[len(b)-1] != '\n' {
		buf.WriteByte('\n')
	}
	return buf.Bytes()
}

func removeLegacyParentFlatten(appRoot string) {
	abs, err := filepath.Abs(appRoot)
	if err != nil {
		return
	}
	parent := filepath.Dir(abs)
	if filepath.Base(parent) != "tui" {
		return
	}
	ents, err := os.ReadDir(parent)
	if err != nil {
		return
	}
	for _, e := range ents {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		_ = os.Remove(filepath.Join(parent, e.Name()))
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
